name: Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Pack NuGet package
        run: dotnet pack --configuration Release --output ./artifacts

      - name: Publish NuGet package
        uses: nuget/nuget-push@v2
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          nuget-source: https://api.nuget.org/v3/index.json
          package: './artifacts/*.nupkg'
